#ifndef __SMARTIO_H__
#define __SMARTIO_H__

enum SmartioErr {
	SMARTIO_SUCCESS,
	SMARTIO_ILLEGAL_MODULE_INDEX,
	SMARTIO_ILLEGAL_ATTRIBUTE_INDEX,
	SMARTIO_NO_PERMISSION,
	SMARTIO_ILLEGAL_VALUE,
	SMARTIO_VALUE_TYPE_MISMATCH,
	SMARTIO_ILLEGAL_COMMAND,
	SMARTIO_ILLEGAL_ARRAY_INDEX
};

enum smartio_cmds {
	SMARTIO_GET_NO_OF_MODULES = 1,
	SMARTIO_GET_NO_OF_ATTRIBUTES,
	SMARTIO_GET_ATTRIBUTE_DEFINITION,
	SMARTIO_GET_ATTR_VALUE,
	SMARTIO_SET_ATTR_VALUE,
	SMARTIO_GET_STRING
};

#define SMARTIO_DATA_SIZE 31

#endif
